/** A family member who can be assigned to events. */
export interface FamilyMember {
  id: string;
  name: string;
  /** Hex color string (e.g. '#ff0000') used to visually identify this member. */
  color: string;
  phone?: string;
}

/** The type of a calendar event. */
export type EventType =
  | 'shift'
  | 'treatment'
  | 'visit'
  | 'parent-note'
  | 'parent-coverage'
  | 'gap';

/** Fixed background colors for each event type (from design system). */
export const EVENT_COLORS: Record<EventType, string> = {
  shift: '#1a73e8',
  treatment: '#e67c00',
  visit: '#0f9d58',
  'parent-note': '#a142f4',
  'parent-coverage': '#fbbc04',
  gap: '#d93025',
};

/** Hebrew display labels for each event type. */
export const EVENT_LABELS: Record<EventType, string> = {
  shift: 'משמרת',
  treatment: 'טיפול',
  visit: 'ביקור',
  'parent-note': 'הורים',
  'parent-coverage': 'הורים עם המטופל',
  gap: 'חסר כיסוי משמרת',
};

/** A single calendar event for a given date and time range. */
export interface CalendarEvent {
  id: string;
  /** ISO 8601 date string (e.g. '2026-03-04'). */
  date: string;
  /** Start time in HH:MM 24-hour format. */
  startTime: string;
  /** End time in HH:MM 24-hour format. */
  endTime: string;
  type: EventType;
  /** Null when no family member is assigned to this event. */
  familyMemberId: string | null;
  /** Optional free-text title. */
  title?: string;
  /** Optional note. */
  note?: string;
  /** Links the two halves of an overnight event that was auto-split. */
  sharedGroupId?: string;
}

/**
 * Returns true if the event spans midnight (endTime lexicographically
 * precedes startTime in HH:MM format).
 */
export function isOvernight(event: CalendarEvent): boolean {
  return event.endTime < event.startTime;
}

/**
 * Returns true if the event is an auto-generated parent-coverage block.
 * Parent-coverage events are never stored — they are computed on the fly.
 */
export function isParentCoverage(event: CalendarEvent): boolean {
  return event.type === 'parent-coverage';
}

/**
 * Returns true if the event is an auto-generated gap block.
 * Gap events indicate uncovered time and are never stored.
 */
export function isGapEvent(event: CalendarEvent): boolean {
  return event.type === 'gap';
}

/**
 * Returns true if the event is auto-generated (parent-coverage or gap)
 * and therefore cannot be edited or deleted.
 */
export function isAutoGenerated(event: CalendarEvent): boolean {
  return event.type === 'parent-coverage' || event.type === 'gap';
}
