'use client';

import { useState, useEffect } from 'react';

import {
  CalendarEvent,
  EventType,
  EVENT_COLORS,
  EVENT_LABELS,
  FamilyMember,
  isAutoGenerated,
} from '@/types';
import { updateEvent, removeEvent, addMember } from '@/src/lib/firestore';
import { Combobox, MEMBER_COLOR_PALETTE } from '@/components/ui/Combobox';

/**
 * Removes all keys with undefined values from an object before
 * sending to Firestore, which does not accept undefined.
 */
function stripUndefined<T extends object>(obj: T): Partial<T> {
  return Object.fromEntries(
    Object.entries(obj).filter(function ([_, v]) {
      return v !== undefined;
    })
  ) as Partial<T>;
}

/** Event types available for user selection (excludes auto-generated types). */
const EDITABLE_EVENT_TYPES: EventType[] = [
  'shift',
  'treatment',
  'visit',
  'parent-note',
];

/**
 * Props for the EditEventPanel component.
 */
export interface EditEventPanelProps {
  /** The event to display or edit. Null when the panel is closed. */
  event: CalendarEvent | null;
  /** Full list of family members available for assignment. */
  members: FamilyMember[];
  /** Called when the panel should close. */
  onClose: () => void;
}

/**
 * RTL slide-in drawer that shows full event details.
 * Editable fields for real events; read-only for parent-coverage and gap events.
 * Slides in from the start side (right in RTL).
 */
export function EditEventPanel({ event, members, onClose }: EditEventPanelProps) {
  const isOpen = event !== null;
  const readOnly = event !== null && isAutoGenerated(event);

  const [type, setType] = useState<EventType>('shift');
  const [date, setDate] = useState('');
  const [startTime, setStartTime] = useState('');
  const [endTime, setEndTime] = useState('');
  const [memberName, setMemberName] = useState('');
  const [title, setTitle] = useState('');
  const [note, setNote] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState(false);

  /**
   * Syncs local form state whenever the selected event changes.
   */
  useEffect(
    function () {
      if (event) {
        setType(event.type);
        setDate(event.date);
        setStartTime(event.startTime);
        setEndTime(event.endTime);

        const matched = members.find((m) => m.id === event.familyMemberId);
        setMemberName(matched ? matched.name : '');

        setTitle(event.title ?? '');
        setNote(event.note ?? '');
        setError(null);
        setSubmitted(false);
      }
    },
    [event, members]
  );

  /**
   * Validates and saves the edited event via the store.
   * Resolves memberName to an existing or newly created FamilyMember.
   */
  async function handleSave(e: React.FormEvent) {
    e.preventDefault();
    setSubmitted(true);
    setError(null);

    if (!memberName.trim()) {
      setError('יש לבחור שם');
      return;
    }

    if (!date || !startTime || !endTime) {
      setError('יש למלא את כל השדות');
      return;
    }

    if (!event) return;

    const existing = members.find(
      (m) => m.name.toLowerCase() === memberName.trim().toLowerCase()
    );

    let familyMemberId: string;

    if (existing) {
      familyMemberId = existing.id;
    } else {
      const randomColor =
        MEMBER_COLOR_PALETTE[
          Math.floor(Math.random() * MEMBER_COLOR_PALETTE.length)
        ];

      const newMember: FamilyMember = {
        id: Date.now().toString(),
        name: memberName.trim(),
        color: randomColor,
      };

      await addMember(newMember);
      familyMemberId = newMember.id;
    }

    await updateEvent(
      event.id,
      stripUndefined({
        type,
        date,
        startTime,
        endTime,
        familyMemberId,
        title: title.trim() || undefined,
        note: note.trim() || undefined,
      })
    );

    onClose();
  }

  /**
   * Deletes the current event from the store and closes the panel.
   */
  function handleDelete() {
    if (!event) return;

    removeEvent(event.id);
    onClose();
  }

  /**
   * Closes the panel when the user clicks the semi-transparent backdrop.
   */
  function handleBackdropClick(e: React.MouseEvent<HTMLDivElement>) {
    if (e.target === e.currentTarget) {
      onClose();
    }
  }

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 z-40 bg-black/20"
          onClick={handleBackdropClick}
          aria-hidden="true"
        />
      )}

      {/* Drawer panel — anchored to the start (right) side in RTL */}
      <div
        role="dialog"
        aria-modal="true"
        aria-label="עריכת אירוע"
        className={`fixed inset-y-0 start-0 z-50 w-full md:max-w-sm bg-white shadow-2xl flex flex-col transform transition-transform duration-300 ${
          isOpen ? 'translate-x-0' : 'translate-x-full'
        }`}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200 bg-white">
          <h2 className="text-base font-semibold text-gray-800">
            {readOnly ? 'פרטי אירוע' : 'עריכת אירוע'}
          </h2>

          <button
            type="button"
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 text-2xl leading-none transition-colors"
            aria-label="סגור"
          >
            ×
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-4 py-4">
          {isOpen && readOnly && (
            <ReadOnlyView event={event!} />
          )}

          {isOpen && !readOnly && (
            <form
              id="edit-event-form"
              onSubmit={handleSave}
              className="flex flex-col gap-3"
            >
              {/* Event type selector */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  סוג אירוע
                </label>

                <div className="grid grid-cols-2 gap-2">
                  {EDITABLE_EVENT_TYPES.map(function (t) {
                    const isSelected = type === t;

                    return (
                      <button
                        key={t}
                        type="button"
                        onClick={function () { setType(t); }}
                        className={`flex items-center gap-2 px-3 py-2 rounded-lg border text-sm font-medium transition-all ${
                          isSelected
                            ? 'border-transparent text-white shadow-sm'
                            : 'border-gray-200 text-gray-700 bg-white hover:border-gray-300'
                        }`}
                        style={isSelected ? { backgroundColor: EVENT_COLORS[t] } : {}}
                      >
                        <span
                          className="w-2.5 h-2.5 rounded-full flex-shrink-0"
                          style={{ backgroundColor: EVENT_COLORS[t] }}
                        />
                        {EVENT_LABELS[t]}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Date picker */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  תאריך
                </label>

                <input
                  type="date"
                  value={date}
                  onChange={function (e) { setDate(e.target.value); }}
                  required
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#1a73e8]"
                />
              </div>

              {/* Time range */}
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    שעת התחלה
                  </label>

                  <input
                    type="time"
                    value={startTime}
                    onChange={function (e) { setStartTime(e.target.value); }}
                    required
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#1a73e8]"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    שעת סיום
                  </label>

                  <input
                    type="time"
                    value={endTime}
                    onChange={function (e) { setEndTime(e.target.value); }}
                    required
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#1a73e8]"
                  />
                </div>
              </div>

              {/* Family member selector — required */}
              <Combobox
                members={members}
                value={memberName}
                onChange={setMemberName}
                required={true}
                submitted={submitted}
              />

              {/* Optional title */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  כותרת (אופציונלי)
                </label>

                <input
                  type="text"
                  value={title}
                  onChange={function (e) { setTitle(e.target.value); }}
                  placeholder="הוסף כותרת..."
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#1a73e8]"
                />
              </div>

              {/* Optional note */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  הערה (אופציונלי)
                </label>

                <textarea
                  value={note}
                  onChange={function (e) { setNote(e.target.value); }}
                  placeholder="הוסף הערה..."
                  rows={2}
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#1a73e8] resize-none"
                />
              </div>

              {error && (
                <p className="text-sm text-red-500">{error}</p>
              )}
            </form>
          )}
        </div>

        {/* Footer — action buttons */}
        {isOpen && !readOnly && (
          <div className="px-4 py-3 border-t border-gray-200 flex flex-col gap-2">
            <button
              type="submit"
              form="edit-event-form"
              className="w-full py-2 rounded-lg text-sm font-semibold text-white transition-colors hover:opacity-90 bg-[#1a73e8]"
            >
              שמירה
            </button>

            <button
              type="button"
              onClick={handleDelete}
              className="w-full py-2 rounded-lg border border-red-200 text-sm font-medium text-red-600 hover:bg-red-50 transition-colors"
            >
              מחיקה
            </button>
          </div>
        )}

        {isOpen && readOnly && (
          <div className="px-4 py-3 border-t border-gray-200">
            <button
              type="button"
              onClick={onClose}
              className="w-full py-2 rounded-lg border border-gray-300 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
            >
              סגור
            </button>
          </div>
        )}
      </div>
    </>
  );
}

/**
 * Props for the ReadOnlyView sub-component.
 */
interface ReadOnlyViewProps {
  event: CalendarEvent;
}

/**
 * Renders a read-only summary of an auto-generated event (parent-coverage or gap).
 */
function ReadOnlyView({ event }: ReadOnlyViewProps) {
  return (
    <div className="flex flex-col gap-3">
      <div
        className="rounded-lg px-3 py-2 text-sm font-semibold"
        style={{
          backgroundColor: EVENT_COLORS[event.type],
          color: event.type === 'parent-coverage' ? '#1a1a1a' : '#ffffff',
        }}
      >
        {EVENT_LABELS[event.type]}
      </div>

      <div className="flex flex-col gap-1 text-sm text-gray-700">
        <div className="flex justify-between">
          <span className="font-medium">תאריך</span>
          <span>{event.date}</span>
        </div>

        <div className="flex justify-between">
          <span className="font-medium">שעות</span>
          <span>
            {event.startTime}–{event.endTime}
          </span>
        </div>
      </div>

      {event.type === 'gap' && (
        <p className="text-xs text-red-600 bg-red-50 border border-red-100 rounded-lg px-3 py-2">
          חסרה משמרת בפרק הזמן הזה. יש להוסיף משמרת כדי לכסות את הזמן.
        </p>
      )}

      {event.type === 'parent-coverage' && (
        <p className="text-xs text-gray-500 bg-gray-50 border border-gray-100 rounded-lg px-3 py-2">
          כיסוי הורים נוצר אוטומטית לזמן שאינו מכוסה על ידי משמרת.
        </p>
      )}
    </div>
  );
}
